### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by CommonGuy** [cwe1ss/opentracing-contrib-dotnet#1]
Are there any plans to release this as a NuGet package (maybe as pre-release)?

**Comment by cwe1ss** [comment]
The .NET framework will get built-in support for distributed tracing via a new `Activity`-API: https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md

I'm currently waiting for it to be finalized / trying to figure out how this affects a .NET OpenTracing implementation. People shouldn't use this library before that because it might lead to some big breaking changes.

I'd appreciate any help though (discussions and code)!

**Comment by stephenpope** [comment]
I was doing some research on OpenTracing and .NET and came across all your work so far (thank you!). You are right, `Activity` seems to be a very (very) close match for whats going on with the tracing.
Im assuming if this is going to be baked into .NET then from an opentracing point-of-view its just a case of serializing the `Activity` objects back to opentracing compatible ones for transport to a collection endpoint.
Interested to hear your thoughts.

**Comment by cwe1ss** [comment]
I'll move this project to opentracing-contrib soon. I'll create a nuget package once it's there and once we've had a discussion about the naming of the packages.

**Comment by cwe1ss** [comment]
I've just migrated this code to https://github.com/opentracing-contrib/csharp-aspnetcore - see https://github.com/opentracing-contrib/csharp-aspnetcore/issues/2 for the discussion regarding the package naming.
